# This YAML file is for storing some parameters about the robot and the battlefield
properties: {
    INF: 999,
    robot_size: 45,
    accuracy: 10,
    xmax: 82, # 81 * 10 / accuracy + 1
    ymax: 51, # 51 * 10 / accuracy + 1
    k_m: 0, # Please add comments about k_m here
}